name: CI
on: [push]

env:
  AWS_REGION: us-east-1

jobs:
  kubectl:
    runs-on: self-hosted
    steps:
      - name: Retrieve secrets from Keeper
        id: ksecrets
        uses: Keeper-Security/ksm-action@master
        with:
          keeper-secret-config: ${{ secrets.KSM_CONFIG }}
          secrets: |-
            fNW6hNUZMImoX21IaGRcQw/field/login > env:AWS_ACCESS_KEY_ID
            fNW6hNUZMImoX21IaGRcQw/field/password > env:AWS_SECRET_ACCESS_KEY
      - name: Setup kubectl
        run: aws eks update-kubeconfig --name eks-rtf-test
      - name: list pods
        run: kubectl get pods --all-namespaces
      - name: delete config
        run: rm ~/.kube/config
