name: CI
on: [push]

jobs:
  kubectl:
    runs-on: selfhosted
    steps:
      - name: Retrieve secrets from Keeper
        id: ksecrets
        uses: Keeper-Security/ksm-action@master
        with:
          keeper-secret-config: ${{ secrets.KSM_CONFIG }}
          secrets: |-
            sd33hj2cVYiRB4TEhAG_jg/field/password > env:TF_TOKEN
            fNW6hNUZMImoX21IaGRcQw/field/login > env:AWS_ACCESS_KEY_ID
            fNW6hNUZMImoX21IaGRcQw/field/password > env:AWS_SECRET_ACCESS_KEY
      - name: Setup kubectl
        run: aws eks update-kubeconfig --region us-east-1 -name eks-rtf-test
      - name: list pods
        run: kubectl get pods --all-namespaces
