name: CI
on: [push]

jobs:
  kubectl:
    runs-on: self-hosted
    steps:
      - name: delete config
        run: run ~/.kube/config
      - name: Retrieve secrets from Keeper
        id: ksecrets
        uses: Keeper-Security/ksm-action@master
        with:
          keeper-secret-config: ${{ secrets.KSM_CONFIG }}
          secrets: |-
            fNW6hNUZMImoX21IaGRcQw/field/login > env:AWS_ACCESS_KEY_ID
            fNW6hNUZMImoX21IaGRcQw/field/password > env:AWS_SECRET_ACCESS_KEY
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Setup kubectl
        run: aws eks update-kubeconfig --name eks-rtf-test
      - name: get identity
        run: aws sts get-caller-identity
      - name: list pods
        run: kubectl get pods --all-namespaces
      - name: delete config
        run: rm ~/.kube/config
